# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: index.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    },
    {
        "key": "wd",
        "value": "360x800",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "c_user",
        "value": "61563543432150",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "xs",
        "value": "28%3AbVyKHlh6RpcT0Q%3A2%3A1758822833%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "fr",
        "value": "04R6DrF4ElP0IsDv3.AWece_7UMkENWLVSdm8jaWgd00xVrmvxXt1kNnKHfsJhDr-Js50.Bo1YFG..AAA.0.0.Bo1YG4.AWcyjYVNF6wzQXJUYgnVkEBD2VE",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "locale",
        "value": "en_GB",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "pas",
        "value": "61563543432150%3AOBn3jI6HJF",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2935%3Btimestamp%3A1758822840",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "fbl_st",
        "value": "101420095%3BT%3A29313715",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B660x360x2",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    }
]        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "fbl_st",
        "value": "101420095%3BT%3A29313715",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B660x360x2",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-25T17:56:56.917Z",
        "lastAccessed": "2025-09-25T17:56:56.917Z"
    }
]
